mysql:
   enabled: true
   auth:
      rootPassword: "admin"
      username: "admin"
      password: "admin"
      database: "automation-assessment"
   primary:
      service:
         port: 3306
   livenessProbe:
      enabled: false
   readinessProbe:
      enabled: false
image:
  registry: docker.io
  repository: mysql
  tag: 8.0
  pullPolicy: IfNotPresent
