mysql:
   enabled: true
   auth:
      rootPassword: "admin"
      username: "admin"
      password: "admin"
      database: "automation-assessment"
   primary:
      service:
         port: 3306
   livenessProbe:
      enabled: false
   readinessProbe:
      enabled: false
image:
  registry: docker.io
  repository: bitnami/mysql
  # override default tag that may not exist for all platforms
  tag: 9.4.0-debian-11-r0
  pullPolicy: IfNotPresent
